version: "3.7"

services:
   mindgem_db:
    container_name: mindgem_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - $HOME/mindgem-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default

networks:
  default:
volumes:
  mindgem-data: